#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "input.h"

#define BUFFER_SIZE 1024 /** Buffer size for `hexcat` output. */
#define ARGUMENT_SIZE 80 /** Buffer size for `hexcat` input arguments. */

#define HEXCAT_PROGRAM "./bin/hexcat"  /** `hexcat` location. */
#define TEST_FILE_PATH "test/data.bin" /** File for test. */

/**
 * @brief Executes the hexcat program with the provided arguments and captures
 * the output.
 *
 * This function constructs a command by combining the program name, arguments,
 * and test file path. It runs the program, captures its output, and stores it
 * in the `output_buffer`.
 *
 * @param input_arguments Arguments to pass to the `hexcat` program.
 * @param output_buffer Pointer to store the captured output.
 * @param output_length Pointer to store the length of the captured output.
 *
 * @return 0 on success, 1 on failure.
 */
int execute_hexcat(const char* input_arguments,
                   char** output_buffer,
                   int* output_length);

/**
 * @brief Displays the actual and expected outputs for comparison.
 *
 * This function prints both the actual output produced by the `hexcat` program
 * and the expected output for comparison purposes.
 *
 * @param actual_output The actual output generated by `hexcat`.
 * @param actual_output_length The length of the actual output.
 * @param expected_output The expected output for comparison.
 * @param expected_output_length The length of the expected output.
 */
void display_output(const char* actual_output,
                    int actual_output_length,
                    const char* expected_output,
                    int expected_output_length);

/**
 * @brief Runs the `hexcat` program and compares its output with the expected
 * result.
 *
 * This function launches the `hexcat` program with the specified arguments,
 * captures its output, and compares it with the expected output. If the output
 * matches, a success message is printed; otherwise, a failure message is shown
 * with the actual and expected outputs.
 *
 * @param input_arguments Arguments to pass to the `hexcat` program.
 * @param expected_output The expected output.
 * @param expected_output_length The length of the expected output.
 */
void run_test(const char* input_arguments,
              const char* expected_output,
              int expected_output_length);

int main() {
    int i;
    printf("Run test.\n");
    for (i = 0; i < NUM_TEST; i++) {
        run_test(TEST_ARGUMENTS[i], EXPECTED_OUTPUTS[i],
                 strlen(EXPECTED_OUTPUTS[i]));
    }
    return 0;
}

void run_test(const char* input_arguments,
              const char* expected_output,
              int expected_output_length) {
    int actual_output_length;
    char* actual_output = NULL;

    if (execute_hexcat(input_arguments, &actual_output,
                       &actual_output_length) != 0) {
        printf("ERROR. Arguments '%s' did not generate output.\n", input_arguments);
        return;
    }

    if (expected_output_length != actual_output_length) {
        printf("FAIL with '%s'. Output size differs.\n", input_arguments);
        display_output(actual_output, actual_output_length, expected_output,
                       expected_output_length);
        free(actual_output);
        return;
    }

    if (strncmp(actual_output, expected_output, actual_output_length) != 0) {
        printf("FAIL with '%s'. Output content differs.\n", input_arguments);
        display_output(actual_output, actual_output_length, expected_output,
                       expected_output_length);
        free(actual_output);
        return;
    }

    free(actual_output);
    printf("SUCCESS. Test '%s' passed.\n", input_arguments);
}

int execute_hexcat(const char* input_arguments,
                   char** output_buffer,
                   int* output_length) {
    FILE* fp;
    char* output = NULL;
    int length = 0;
    char buffer[BUFFER_SIZE];
    char command[ARGUMENT_SIZE];
    int bytes_read;

    /* Construct the command to execute. */
    sprintf(command, "%s %s %s\n", HEXCAT_PROGRAM, input_arguments,
            TEST_FILE_PATH);

    /* Execute the command. */
    fp = popen(command, "r");
    if (!fp) {
        perror("popen");
        return 1;
    }

    /* Allocate memory for the output. */
    output = (char*)malloc(sizeof(char));
    if (!output) {
        fprintf(stderr, "Memory allocation error.\n");
        return 1;
    }
    output[0] = '\0';
    length = 1;

    /* Read the output from the program. */
    while ((bytes_read = fread(buffer, sizeof(char), BUFFER_SIZE, fp)) > 0) {
        /* Reallocate memory and append the new data. */
        length += bytes_read;
        output = (char*)realloc(output, length + 1);  // +1 for null terminator
        if (!output) {
            pclose(fp);
            fprintf(stderr, "Memory allocation error.\n");
            return 1;
        }

        strncat(output, buffer, bytes_read);
    }

    *output_buffer = output;
    *output_length = length - 1;  // Exclude null terminator

    pclose(fp);
    return 0;
}

void display_output(const char* actual_output,
                    int actual_output_length,
                    const char* expected_output,
                    int expected_output_length) {
    printf("--------------------ACTUAL OUTPUT---------------------\n");
    printf("%.*s", actual_output_length, actual_output);
    printf("\n-------------------EXPECTED OUTPUT-------------------\n");
    printf("%.*s", expected_output_length, expected_output);
    printf("\n------------------------------------------------------\n");
}
